import os

path = r"e:\PICT Techfiesta\BudgetBandhu\budget-bandhu-rag\api\routes\literacy.py"

parts = []
parts.append('"""AI Literacy Hub - Personalized financial lessons via Phi-3.5 RAG."""')
parts.append("from fastapi import APIRouter, HTTPException, Depends")
parts.append("from pydantic import BaseModel")
parts.append("from datetime import datetime, timedelta")
parts.append("from collections import defaultdict")
parts.append("import json, re, logging, uuid")
parts.append("import requests as http_requests")
parts.append("from api.database import get_database")
parts.append("")
parts.append("logger = logging.getLogger(__name__)")
parts.append('router = APIRouter(prefix="/api/v1/literacy", tags=["Literacy"])')
parts.append('OLLAMA_URL = "http://localhost:11434/api/generate"')
parts.append('OLLAMA_MODEL = "budget-bandhu"')
parts.append("")
parts.append("")
parts.append("class LessonRequest(BaseModel):")
parts.append("    user_id: str")
parts.append("    topic: str")
parts.append('    difficulty: str = "beginner"')
parts.append('    session_id: str = ""')
parts.append("")
parts.append("")
parts.append("class QuizResultRequest(BaseModel):")
parts.append("    user_id: str")
parts.append("    session_id: str")
parts.append("    score: int")
parts.append("    total: int")
parts.append("")
parts.append("")
parts.append("async def _build_user_context(db, user_id):")
parts.append("    thirty_days_ago = datetime.utcnow() - timedelta(days=30)")
parts.append('    cursor = db["transactions"].find({"user_id": user_id, "type": "debit", "created_at": {"$gte": thirty_days_ago}})')
parts.append("    txns = await cursor.to_list(length=500)")
parts.append('    user = await db["users"].find_one({"_id": user_id})')
parts.append('    income = user.get("income", 50000) if user else 50000')
parts.append("    cat_spend = defaultdict(float)")
parts.append("    total = 0.0")
parts.append("    for t in txns:")
parts.append('        cat_spend[t.get("category", "Other")] += t.get("amount", 0)')
parts.append('        total += t.get("amount", 0)')
parts.append("    top3 = sorted(cat_spend.items(), key=lambda x: x[1], reverse=True)[:3]")
parts.append("    rate = max(0, round((income - total) / income * 100, 1)) if income > 0 else 0")
parts.append('    budget = await db["budgets"].find_one({"user_id": user_id})')
parts.append("    overspent = []")
parts.append("    budget_health = 100")
parts.append("    if budget:")
parts.append('        total_alloc = sum(a.get("allocated", 0) for a in budget.get("allocations", []))')
parts.append("        budget_health = round(total / total_alloc * 100, 1) if total_alloc > 0 else 100")
parts.append('        for alloc in budget.get("allocations", []):')
parts.append('            if cat_spend.get(alloc["category"], 0) > alloc.get("allocated", 0):')
parts.append('                overspent.append(alloc["category"])')
parts.append('    return {"income": income, "total_spend": total, "top_cats": top3, "savings_rate": rate,')
parts.append('            "overspent": overspent, "budget_health": budget_health, "category_spend": dict(cat_spend)}')
parts.append("")
parts.append("")
parts.append("def _extract_json(text):")
parts.append("    try:")
parts.append("        return json.loads(text)")
parts.append("    except Exception:")
parts.append("        pass")
parts.append(r"    m = re.search(r'\{[\s\S]*\}', text)")
parts.append("    if m:")
parts.append("        try:")
parts.append("            return json.loads(m.group(0))")
parts.append("        except Exception:")
parts.append("            pass")
parts.append("    return {}")
parts.append("")
parts.append("")
parts.append("def _fallback_lesson(topic, ctx):")
parts.append('    top_cat = ctx["top_cats"][0][0] if ctx["top_cats"] else "general expenses"')
parts.append('    top_amt = ctx["top_cats"][0][1] if ctx["top_cats"] else 0')
parts.append('    content = "Understanding finances is key. "')
parts.append('    content += "This month: Rs {:.0f}. ".format(ctx["total_spend"])')
parts.append('    content += "Top: {} Rs {:.0f}. ".format(top_cat, top_amt)')
parts.append('    content += "Target 20% savings. Current: {}%.".format(ctx["savings_rate"])')
parts.append("    return {")
parts.append('        "lesson": {')
parts.append('            "title": topic + ": Getting Started",')
parts.append('            "content": content,')
parts.append('            "key_points": ["Track every expense", "Aim for 20% savings", "Review weekly"],')
parts.append('            "personalized_example": "Top spend: {} Rs {:.0f}.".format(top_cat, top_amt),')
parts.append('            "estimated_minutes": 10,')
parts.append("        },")
parts.append('        "quiz": {"questions": [')
parts.append('            {"q": "Recommended savings rate?", "options": ["5%","10%","20%","50%"], "correct": 2, "explanation": "20% is recommended."},')
parts.append('            {"q": "Your top category?", "options": [top_cat,"Travel","Rent","Other"], "correct": 0, "explanation": top_cat + " is highest."},')
parts.append('            {"q": "50/30/20 rule is?", "options": ["Tax","Budget","Investment","Loan"], "correct": 1, "explanation": "50% needs, 30% wants, 20% savings."},')
parts.append('            {"q": "Review how often?", "options": ["Yearly","Monthly","Weekly","Never"], "correct": 2, "explanation": "Weekly helps catch overspend."},')
parts.append("        ]}")
parts.append("    }")
parts.append("")
parts.append("")
parts.append('@router.post("/lesson")')
parts.append("async def generate_lesson(req: LessonRequest, db=Depends(get_database)):")
parts.append('    """Generate a personalized financial literacy lesson with quiz using Phi-3.5."""')
parts.append("    try:")
parts.append("        ctx = await _build_user_context(db, req.user_id)")
parts.append('        top_str = ", ".join("{} Rs{:,.0f}".format(c[0], c[1]) for c in ctx["top_cats"]) or "N/A"')
parts.append('        overspent_str = ", ".join(ctx["overspent"]) or "None"')
parts.append("        sid = req.session_id or str(uuid.uuid4())")
parts.append("")
parts.append("        # Build prompt")
parts.append("        p = []")
parts.append('        p.append("You are BudgetBandhu financial literacy coach.")')
parts.append('        p.append("Generate a personalized {} lesson on \\"{}\\" for an Indian earner.".format(req.difficulty, req.topic))')
parts.append('        p.append("")')
parts.append('        p.append("USER REAL FINANCIAL DATA:")')
parts.append('        p.append("- Monthly income: Rs{:,.0f}".format(ctx["income"]))')
parts.append('        p.append("- Top spending: {}".format(top_str))')
parts.append('        p.append("- Savings rate: {}%".format(ctx["savings_rate"]))')
parts.append('        p.append("- Overspent: {}".format(overspent_str))')
parts.append('        p.append("- Budget health: {}% used".format(ctx["budget_health"]))')
parts.append('        p.append("")')
parts.append('        p.append("RULES:")')
parts.append('        p.append("1. Write a 150-200 word lesson referencing THEIR actual numbers")')
parts.append('        p.append("2. Give 3 key_points as bullets")')
parts.append('        p.append("3. Give 1 personalized_example using their real data")')
parts.append('        p.append("4. Create 4 quiz questions derived from their actual spending")')
parts.append('        p.append("")')
parts.append('        p.append("Respond ONLY in this exact JSON format:")')
parts.append('        schema = (\'{"lesson":{"title":"...","content":"...","key_points":["...","...","..."],\'')
parts.append('                  \'"personalized_example":"...","estimated_minutes":15},\'')
parts.append('                  \'"quiz":{"questions":[{"q":"...","options":["...","...","...","..."],"correct":0,"explanation":"..."},\'')
parts.append('                  \'{"q":"...","options":["...","...","...","..."],"correct":1,"explanation":"..."},\'')
parts.append('                  \'{"q":"...","options":["...","...","...","..."],"correct":2,"explanation":"..."},\'')
parts.append('                  \'{"q":"...","options":["...","...","...","..."],"correct":3,"explanation":"..."}]}}\')')
parts.append('        p.append(schema)')
parts.append('        prompt = "\\n".join(p)')
parts.append("")
parts.append("        # Call Ollama")
parts.append("        lesson_data = {}")
parts.append("        try:")
parts.append("            resp = http_requests.post(")
parts.append("                OLLAMA_URL,")
parts.append('                json={"model": OLLAMA_MODEL, "prompt": prompt, "stream": False,')
parts.append('                      "options": {"temperature": 0.7, "num_predict": 1024}},')
parts.append("                timeout=60")
parts.append("            )")
parts.append("            resp.raise_for_status()")
parts.append('            raw = resp.json().get("response", "")')
parts.append("            lesson_data = _extract_json(raw)")
parts.append("        except Exception as e:")
parts.append('            logger.warning("[Literacy] Ollama call failed: {}".format(e))')
parts.append("")
parts.append("        if not lesson_data.get('lesson'):")
parts.append("            lesson_data = _fallback_lesson(req.topic, ctx)")
parts.append("")
parts.append("        # Save session to MongoDB")
parts.append("        try:")
parts.append('            await db["literacy_sessions"].insert_one({')
parts.append('                "session_id": sid,')
parts.append('                "user_id": req.user_id,')
parts.append('                "topic": req.topic,')
parts.append('                "difficulty": req.difficulty,')
parts.append('                "completed_at": datetime.utcnow(),')
parts.append('                "quiz_score": None,')
parts.append('                "lesson_title": lesson_data.get("lesson", {}).get("title", req.topic),')
parts.append("            })")
parts.append("        except Exception as e:")
parts.append('            logger.warning("[Literacy] Session save failed: {}".format(e))')
parts.append("")
parts.append("        return {**lesson_data, \"session_id\": sid}")
parts.append("")
parts.append("    except Exception as e:")
parts.append('        logger.error("[Literacy] Lesson error: {}".format(e))')
parts.append("        raise HTTPException(status_code=503, detail=\"AI lesson generation failed, try again\")")
parts.append("")
parts.append("")
parts.append('@router.get("/history/{user_id}")')
parts.append("async def get_lesson_history(user_id: str, db=Depends(get_database)):")
parts.append('    """Returns last 10 completed literacy sessions for a user."""')
parts.append("    try:")
parts.append('        cursor = db["literacy_sessions"].find({"user_id": user_id}).sort("completed_at", -1).limit(10)')
parts.append("        sessions = await cursor.to_list(length=10)")
parts.append("        result = []")
parts.append("        for s in sessions:")
parts.append("            result.append({")
parts.append('                "session_id": s.get("session_id", str(s.get("_id", ""))),')
parts.append('                "topic": s.get("topic", ""),')
parts.append('                "difficulty": s.get("difficulty", "beginner"),')
parts.append('                "completed_at": s.get("completed_at", datetime.utcnow()).isoformat(),')
parts.append('                "quiz_score": s.get("quiz_score"),')
parts.append('                "lesson_title": s.get("lesson_title", ""),')
parts.append("            })")
parts.append("        return result")
parts.append("    except Exception as e:")
parts.append("        raise HTTPException(status_code=500, detail=str(e))")
parts.append("")
parts.append("")
parts.append('@router.post("/quiz-result")')
parts.append("async def save_quiz_result(req: QuizResultRequest, db=Depends(get_database)):")
parts.append('    """Save quiz score for a completed literacy session."""')
parts.append("    try:")
parts.append('        pct = round(req.score / max(req.total, 1) * 100, 1)')
parts.append('        await db["literacy_sessions"].update_one(')
parts.append('            {"session_id": req.session_id, "user_id": req.user_id},')
parts.append('            {"$set": {"quiz_score": req.score, "quiz_total": req.total, "quiz_pct": pct, "quiz_completed_at": datetime.utcnow()}},')
parts.append('            upsert=False,')
parts.append("        )")
parts.append('        return {"status": "ok", "score": req.score, "total": req.total, "percentage": pct}')
parts.append("    except Exception as e:")
parts.append("        raise HTTPException(status_code=500, detail=str(e))")
parts.append("")

with open(path, "w", encoding="utf-8") as f:
    f.write("\n".join(parts))

print("literacy.py written successfully -", len(parts), "lines")
